//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        public int IdMascota { get; set; }
        public int IdCliente { get; set; }
        public string Alias { get; set; }
        public string Especie { get; set; }
        public string Raza { get; set; }
        public string ColorPelo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
    }
}
