//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacunas
    {
        public int Id { get; set; }
        public Nullable<int> IdMascota { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Enfermedad { get; set; }
        public Nullable<System.DateTime> FechaProxima { get; set; }
    }
}
